# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cam_cloud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cam_cloud.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63\x61m_cloud.proto\"-\n\x0f\x44\x65ployOpRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63rop\x18\x02 \x01(\t\"#\n\x0fInitDivaRequest\x12\x10\n\x08img_path\x18\x01 \x01(\t\"\x1f\n\x0fGetFrameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x05\x46rame\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x15\n\x06StrMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xab\x01\n\nDivaCamera\x12\'\n\x08InitDiva\x12\x10.InitDivaRequest\x1a\x07.StrMsg\"\x00\x12&\n\x08GetFrame\x12\x10.GetFrameRequest\x1a\x06.Frame\"\x00\x12\x1d\n\x08\x44\x65ployOp\x12\x06.Chunk\x1a\x07.StrMsg\"\x00\x12-\n\x0e\x44\x65ployOpNotify\x12\x10.DeployOpRequest\x1a\x07.StrMsg\"\x00\x62\x06proto3')
)




_DEPLOYOPREQUEST = _descriptor.Descriptor(
  name='DeployOpRequest',
  full_name='DeployOpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DeployOpRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crop', full_name='DeployOpRequest.crop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=64,
)


_INITDIVAREQUEST = _descriptor.Descriptor(
  name='InitDivaRequest',
  full_name='InitDivaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img_path', full_name='InitDivaRequest.img_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=101,
)


_GETFRAMEREQUEST = _descriptor.Descriptor(
  name='GetFrameRequest',
  full_name='GetFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GetFrameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=134,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Frame.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Frame.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=171,
)


_STRMSG = _descriptor.Descriptor(
  name='StrMsg',
  full_name='StrMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='StrMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=194,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Chunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['DeployOpRequest'] = _DEPLOYOPREQUEST
DESCRIPTOR.message_types_by_name['InitDivaRequest'] = _INITDIVAREQUEST
DESCRIPTOR.message_types_by_name['GetFrameRequest'] = _GETFRAMEREQUEST
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['StrMsg'] = _STRMSG
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeployOpRequest = _reflection.GeneratedProtocolMessageType('DeployOpRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYOPREQUEST,
  __module__ = 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:DeployOpRequest)
  ))
_sym_db.RegisterMessage(DeployOpRequest)

InitDivaRequest = _reflection.GeneratedProtocolMessageType('InitDivaRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITDIVAREQUEST,
  __module__ = 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:InitDivaRequest)
  ))
_sym_db.RegisterMessage(InitDivaRequest)

GetFrameRequest = _reflection.GeneratedProtocolMessageType('GetFrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFRAMEREQUEST,
  __module__ = 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:GetFrameRequest)
  ))
_sym_db.RegisterMessage(GetFrameRequest)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  ))
_sym_db.RegisterMessage(Frame)

StrMsg = _reflection.GeneratedProtocolMessageType('StrMsg', (_message.Message,), dict(
  DESCRIPTOR = _STRMSG,
  __module__ = 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:StrMsg)
  ))
_sym_db.RegisterMessage(StrMsg)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  ))
_sym_db.RegisterMessage(Chunk)



_DIVACAMERA = _descriptor.ServiceDescriptor(
  name='DivaCamera',
  full_name='DivaCamera',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=220,
  serialized_end=391,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitDiva',
    full_name='DivaCamera.InitDiva',
    index=0,
    containing_service=None,
    input_type=_INITDIVAREQUEST,
    output_type=_STRMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='DivaCamera.GetFrame',
    index=1,
    containing_service=None,
    input_type=_GETFRAMEREQUEST,
    output_type=_FRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeployOp',
    full_name='DivaCamera.DeployOp',
    index=2,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_STRMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeployOpNotify',
    full_name='DivaCamera.DeployOpNotify',
    index=3,
    containing_service=None,
    input_type=_DEPLOYOPREQUEST,
    output_type=_STRMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIVACAMERA)

DESCRIPTOR.services_by_name['DivaCamera'] = _DIVACAMERA

# @@protoc_insertion_point(module_scope)
