# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cam_cloud.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cam_cloud.proto',
  package='camera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x63\x61m_cloud.proto\x12\x06\x63\x61mera\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"E\n\x0cVideoRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x12\n\nvideo_name\x18\x03 \x01(\t\"N\n\rVideoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1b\n\x05video\x18\x03 \x01(\x0b\x32\x0c.common.File\"-\n\x0f\x44\x65ployOpRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63rop\x18\x02 \x01(\t\"#\n\x0fInitDivaRequest\x12\x10\n\x08img_path\x18\x01 \x01(\t\"\x1f\n\x0fGetFrameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x05\x46rame\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x15\n\x06StrMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xa8\x03\n\nDivaCamera\x12\x35\n\x08InitDiva\x12\x17.camera.InitDivaRequest\x1a\x0e.camera.StrMsg\"\x00\x12\x34\n\x08GetFrame\x12\x17.camera.GetFrameRequest\x1a\r.camera.Frame\"\x00\x12+\n\x08\x44\x65ployOp\x12\r.camera.Chunk\x1a\x0e.camera.StrMsg\"\x00\x12;\n\x0e\x44\x65ployOpNotify\x12\x17.camera.DeployOpRequest\x1a\x0e.camera.StrMsg\"\x00\x12\x41\n\rDownloadVideo\x12\x17.camera.DeployOpRequest\x1a\x15.camera.VideoResponse\"\x00\x12?\n\nget_videos\x12\x16.google.protobuf.Empty\x1a\x17.common.get_videos_resp\"\x00\x12?\n\rprocess_video\x12\x14.common.VideoRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_VIDEOREQUEST = _descriptor.Descriptor(
  name='VideoRequest',
  full_name='camera.VideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='camera.VideoRequest.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='camera.VideoRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_name', full_name='camera.VideoRequest.video_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=139,
)


_VIDEORESPONSE = _descriptor.Descriptor(
  name='VideoResponse',
  full_name='camera.VideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='camera.VideoResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='camera.VideoResponse.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video', full_name='camera.VideoResponse.video', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=219,
)


_DEPLOYOPREQUEST = _descriptor.Descriptor(
  name='DeployOpRequest',
  full_name='camera.DeployOpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='camera.DeployOpRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crop', full_name='camera.DeployOpRequest.crop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=266,
)


_INITDIVAREQUEST = _descriptor.Descriptor(
  name='InitDivaRequest',
  full_name='camera.InitDivaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img_path', full_name='camera.InitDivaRequest.img_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=303,
)


_GETFRAMEREQUEST = _descriptor.Descriptor(
  name='GetFrameRequest',
  full_name='camera.GetFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='camera.GetFrameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=336,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='camera.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='camera.Frame.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='camera.Frame.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=373,
)


_STRMSG = _descriptor.Descriptor(
  name='StrMsg',
  full_name='camera.StrMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='camera.StrMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=396,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='camera.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='camera.Chunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=419,
)

_VIDEORESPONSE.fields_by_name['video'].message_type = common__pb2._FILE
DESCRIPTOR.message_types_by_name['VideoRequest'] = _VIDEOREQUEST
DESCRIPTOR.message_types_by_name['VideoResponse'] = _VIDEORESPONSE
DESCRIPTOR.message_types_by_name['DeployOpRequest'] = _DEPLOYOPREQUEST
DESCRIPTOR.message_types_by_name['InitDivaRequest'] = _INITDIVAREQUEST
DESCRIPTOR.message_types_by_name['GetFrameRequest'] = _GETFRAMEREQUEST
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['StrMsg'] = _STRMSG
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoRequest = _reflection.GeneratedProtocolMessageType('VideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOREQUEST,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.VideoRequest)
  })
_sym_db.RegisterMessage(VideoRequest)

VideoResponse = _reflection.GeneratedProtocolMessageType('VideoResponse', (_message.Message,), {
  'DESCRIPTOR' : _VIDEORESPONSE,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.VideoResponse)
  })
_sym_db.RegisterMessage(VideoResponse)

DeployOpRequest = _reflection.GeneratedProtocolMessageType('DeployOpRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPLOYOPREQUEST,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.DeployOpRequest)
  })
_sym_db.RegisterMessage(DeployOpRequest)

InitDivaRequest = _reflection.GeneratedProtocolMessageType('InitDivaRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITDIVAREQUEST,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.InitDivaRequest)
  })
_sym_db.RegisterMessage(InitDivaRequest)

GetFrameRequest = _reflection.GeneratedProtocolMessageType('GetFrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFRAMEREQUEST,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.GetFrameRequest)
  })
_sym_db.RegisterMessage(GetFrameRequest)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.Frame)
  })
_sym_db.RegisterMessage(Frame)

StrMsg = _reflection.GeneratedProtocolMessageType('StrMsg', (_message.Message,), {
  'DESCRIPTOR' : _STRMSG,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.StrMsg)
  })
_sym_db.RegisterMessage(StrMsg)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'cam_cloud_pb2'
  # @@protoc_insertion_point(class_scope:camera.Chunk)
  })
_sym_db.RegisterMessage(Chunk)



_DIVACAMERA = _descriptor.ServiceDescriptor(
  name='DivaCamera',
  full_name='camera.DivaCamera',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=422,
  serialized_end=846,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitDiva',
    full_name='camera.DivaCamera.InitDiva',
    index=0,
    containing_service=None,
    input_type=_INITDIVAREQUEST,
    output_type=_STRMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='camera.DivaCamera.GetFrame',
    index=1,
    containing_service=None,
    input_type=_GETFRAMEREQUEST,
    output_type=_FRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeployOp',
    full_name='camera.DivaCamera.DeployOp',
    index=2,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_STRMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeployOpNotify',
    full_name='camera.DivaCamera.DeployOpNotify',
    index=3,
    containing_service=None,
    input_type=_DEPLOYOPREQUEST,
    output_type=_STRMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadVideo',
    full_name='camera.DivaCamera.DownloadVideo',
    index=4,
    containing_service=None,
    input_type=_DEPLOYOPREQUEST,
    output_type=_VIDEORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_videos',
    full_name='camera.DivaCamera.get_videos',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=common__pb2._GET_VIDEOS_RESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='process_video',
    full_name='camera.DivaCamera.process_video',
    index=6,
    containing_service=None,
    input_type=common__pb2._VIDEOREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIVACAMERA)

DESCRIPTOR.services_by_name['DivaCamera'] = _DIVACAMERA

# @@protoc_insertion_point(module_scope)
