# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: det-yolov3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='det-yolov3.proto',
  package='det_yolov3',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x65t-yolov3.proto\x12\ndet_yolov3\"E\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\"N\n\x0f\x44\x65tFrameRequest\x12 \n\x05image\x18\x01 \x01(\x0b\x32\x11.det_yolov3.Image\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x63ls\x18\x03 \x01(\t\"\x14\n\x05Score\x12\x0b\n\x03res\x18\x01 \x01(\t\"U\n\x10\x44\x65tectionRequest\x12 \n\x05image\x18\x01 \x01(\x0b\x32\x11.det_yolov3.Image\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tthreshold\x18\x03 \x01(\x02\"M\n\x07\x45lement\x12\x12\n\nconfidence\x18\x01 \x01(\x01\x12\n\n\x02x1\x18\x02 \x01(\x05\x12\n\n\x02y1\x18\x03 \x01(\x05\x12\n\n\x02x2\x18\x04 \x01(\x05\x12\n\n\x02y2\x18\x05 \x01(\x05\"D\n\x08\x45lements\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12$\n\x07\x65lement\x18\x02 \x03(\x0b\x32\x13.det_yolov3.Element\"9\n\x0f\x44\x65tectionOutput\x12&\n\x08\x65lements\x18\x01 \x03(\x0b\x32\x14.det_yolov3.Elements2\x90\x01\n\tDetYOLOv3\x12<\n\x08\x44\x65tFrame\x12\x1b.det_yolov3.DetFrameRequest\x1a\x11.det_yolov3.Score\"\x00\x12\x45\n\x06\x44\x65tect\x12\x1c.det_yolov3.DetectionRequest\x1a\x1b.det_yolov3.DetectionOutput\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='det_yolov3.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='det_yolov3.Image.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='det_yolov3.Image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='det_yolov3.Image.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='det_yolov3.Image.channel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=101,
)


_DETFRAMEREQUEST = _descriptor.Descriptor(
  name='DetFrameRequest',
  full_name='det_yolov3.DetFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='det_yolov3.DetFrameRequest.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='det_yolov3.DetFrameRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cls', full_name='det_yolov3.DetFrameRequest.cls', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=181,
)


_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='det_yolov3.Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='det_yolov3.Score.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=203,
)


_DETECTIONREQUEST = _descriptor.Descriptor(
  name='DetectionRequest',
  full_name='det_yolov3.DetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='det_yolov3.DetectionRequest.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='det_yolov3.DetectionRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='det_yolov3.DetectionRequest.threshold', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=290,
)


_ELEMENT = _descriptor.Descriptor(
  name='Element',
  full_name='det_yolov3.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='det_yolov3.Element.confidence', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x1', full_name='det_yolov3.Element.x1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='det_yolov3.Element.y1', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='det_yolov3.Element.x2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y2', full_name='det_yolov3.Element.y2', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=369,
)


_ELEMENTS = _descriptor.Descriptor(
  name='Elements',
  full_name='det_yolov3.Elements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_name', full_name='det_yolov3.Elements.class_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='element', full_name='det_yolov3.Elements.element', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=439,
)


_DETECTIONOUTPUT = _descriptor.Descriptor(
  name='DetectionOutput',
  full_name='det_yolov3.DetectionOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='det_yolov3.DetectionOutput.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=498,
)

_DETFRAMEREQUEST.fields_by_name['image'].message_type = _IMAGE
_DETECTIONREQUEST.fields_by_name['image'].message_type = _IMAGE
_ELEMENTS.fields_by_name['element'].message_type = _ELEMENT
_DETECTIONOUTPUT.fields_by_name['elements'].message_type = _ELEMENTS
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['DetFrameRequest'] = _DETFRAMEREQUEST
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
DESCRIPTOR.message_types_by_name['DetectionRequest'] = _DETECTIONREQUEST
DESCRIPTOR.message_types_by_name['Element'] = _ELEMENT
DESCRIPTOR.message_types_by_name['Elements'] = _ELEMENTS
DESCRIPTOR.message_types_by_name['DetectionOutput'] = _DETECTIONOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.Image)
  })
_sym_db.RegisterMessage(Image)

DetFrameRequest = _reflection.GeneratedProtocolMessageType('DetFrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETFRAMEREQUEST,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.DetFrameRequest)
  })
_sym_db.RegisterMessage(DetFrameRequest)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
  'DESCRIPTOR' : _SCORE,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.Score)
  })
_sym_db.RegisterMessage(Score)

DetectionRequest = _reflection.GeneratedProtocolMessageType('DetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONREQUEST,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.DetectionRequest)
  })
_sym_db.RegisterMessage(DetectionRequest)

Element = _reflection.GeneratedProtocolMessageType('Element', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENT,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.Element)
  })
_sym_db.RegisterMessage(Element)

Elements = _reflection.GeneratedProtocolMessageType('Elements', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTS,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.Elements)
  })
_sym_db.RegisterMessage(Elements)

DetectionOutput = _reflection.GeneratedProtocolMessageType('DetectionOutput', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONOUTPUT,
  '__module__' : 'det_yolov3_pb2'
  # @@protoc_insertion_point(class_scope:det_yolov3.DetectionOutput)
  })
_sym_db.RegisterMessage(DetectionOutput)



_DETYOLOV3 = _descriptor.ServiceDescriptor(
  name='DetYOLOv3',
  full_name='det_yolov3.DetYOLOv3',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=501,
  serialized_end=645,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetFrame',
    full_name='det_yolov3.DetYOLOv3.DetFrame',
    index=0,
    containing_service=None,
    input_type=_DETFRAMEREQUEST,
    output_type=_SCORE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='det_yolov3.DetYOLOv3.Detect',
    index=1,
    containing_service=None,
    input_type=_DETECTIONREQUEST,
    output_type=_DETECTIONOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETYOLOV3)

DESCRIPTOR.services_by_name['DetYOLOv3'] = _DETYOLOV3

# @@protoc_insertion_point(module_scope)
