# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_diva.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_diva.proto',
  package='server_diva',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11server_diva.proto\x12\x0bserver_diva\x1a\x1bgoogle/protobuf/empty.proto\"X\n\x10\x64\x65tection_result\x12(\n\x06retval\x18\x01 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\t\n\x07payload\"<\n\x11object_video_pair\x12\x13\n\x0bobject_name\x18\x03 \x01(\t\x12\x12\n\nvideo_name\x18\x04 \x01(\t2h\n\x0bserver_diva\x12Y\n\x16\x64\x65tect_object_in_video\x12\x1e.server_diva.object_video_pair\x1a\x1d.server_diva.detection_result\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DETECTION_RESULT = _descriptor.Descriptor(
  name='detection_result',
  full_name='server_diva.detection_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='server_diva.detection_result.retval', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='server_diva.detection_result.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='server_diva.detection_result.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=63,
  serialized_end=151,
)


_OBJECT_VIDEO_PAIR = _descriptor.Descriptor(
  name='object_video_pair',
  full_name='server_diva.object_video_pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_name', full_name='server_diva.object_video_pair.object_name', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_name', full_name='server_diva.object_video_pair.video_name', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=213,
)

_DETECTION_RESULT.fields_by_name['retval'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_DETECTION_RESULT.oneofs_by_name['payload'].fields.append(
  _DETECTION_RESULT.fields_by_name['retval'])
_DETECTION_RESULT.fields_by_name['retval'].containing_oneof = _DETECTION_RESULT.oneofs_by_name['payload']
_DETECTION_RESULT.oneofs_by_name['payload'].fields.append(
  _DETECTION_RESULT.fields_by_name['error'])
_DETECTION_RESULT.fields_by_name['error'].containing_oneof = _DETECTION_RESULT.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['detection_result'] = _DETECTION_RESULT
DESCRIPTOR.message_types_by_name['object_video_pair'] = _OBJECT_VIDEO_PAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

detection_result = _reflection.GeneratedProtocolMessageType('detection_result', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION_RESULT,
  '__module__' : 'server_diva_pb2'
  # @@protoc_insertion_point(class_scope:server_diva.detection_result)
  })
_sym_db.RegisterMessage(detection_result)

object_video_pair = _reflection.GeneratedProtocolMessageType('object_video_pair', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT_VIDEO_PAIR,
  '__module__' : 'server_diva_pb2'
  # @@protoc_insertion_point(class_scope:server_diva.object_video_pair)
  })
_sym_db.RegisterMessage(object_video_pair)



_SERVER_DIVA = _descriptor.ServiceDescriptor(
  name='server_diva',
  full_name='server_diva.server_diva',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=215,
  serialized_end=319,
  methods=[
  _descriptor.MethodDescriptor(
    name='detect_object_in_video',
    full_name='server_diva.server_diva.detect_object_in_video',
    index=0,
    containing_service=None,
    input_type=_OBJECT_VIDEO_PAIR,
    output_type=_DETECTION_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER_DIVA)

DESCRIPTOR.services_by_name['server_diva'] = _SERVER_DIVA

# @@protoc_insertion_point(module_scope)
