# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import server_diva_pb2 as server__diva__pb2


class server_divaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.request_frame_path = channel.unary_unary(
        '/server_diva.server_diva/request_frame_path',
        request_serializer=server__diva__pb2.query_statement.SerializeToString,
        response_deserializer=server__diva__pb2.directory.FromString,
        )
    self.detect_object_in_video = channel.unary_unary(
        '/server_diva.server_diva/detect_object_in_video',
        request_serializer=server__diva__pb2.object_video_pair.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class server_divaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def request_frame_path(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def detect_object_in_video(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_server_divaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'request_frame_path': grpc.unary_unary_rpc_method_handler(
          servicer.request_frame_path,
          request_deserializer=server__diva__pb2.query_statement.FromString,
          response_serializer=server__diva__pb2.directory.SerializeToString,
      ),
      'detect_object_in_video': grpc.unary_unary_rpc_method_handler(
          servicer.detect_object_in_video,
          request_deserializer=server__diva__pb2.object_video_pair.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'server_diva.server_diva', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
