# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_diva.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_diva.proto',
  package='server_diva',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11server_diva.proto\x12\x0bserver_diva\"\x1f\n\x0fquery_statement\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\tdirectory\x12\x16\n\x0e\x64irectory_path\x18\x01 \x01(\t2[\n\x0bserver_diva\x12L\n\x12request_frame_path\x12\x1c.server_diva.query_statement\x1a\x16.server_diva.directory\"\x00\x62\x06proto3')
)




_QUERY_STATEMENT = _descriptor.Descriptor(
  name='query_statement',
  full_name='server_diva.query_statement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='server_diva.query_statement.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=65,
)


_DIRECTORY = _descriptor.Descriptor(
  name='directory',
  full_name='server_diva.directory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directory_path', full_name='server_diva.directory.directory_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['query_statement'] = _QUERY_STATEMENT
DESCRIPTOR.message_types_by_name['directory'] = _DIRECTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

query_statement = _reflection.GeneratedProtocolMessageType('query_statement', (_message.Message,), {
  'DESCRIPTOR' : _QUERY_STATEMENT,
  '__module__' : 'server_diva_pb2'
  # @@protoc_insertion_point(class_scope:server_diva.query_statement)
  })
_sym_db.RegisterMessage(query_statement)

directory = _reflection.GeneratedProtocolMessageType('directory', (_message.Message,), {
  'DESCRIPTOR' : _DIRECTORY,
  '__module__' : 'server_diva_pb2'
  # @@protoc_insertion_point(class_scope:server_diva.directory)
  })
_sym_db.RegisterMessage(directory)



_SERVER_DIVA = _descriptor.ServiceDescriptor(
  name='server_diva',
  full_name='server_diva.server_diva',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=104,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='request_frame_path',
    full_name='server_diva.server_diva.request_frame_path',
    index=0,
    containing_service=None,
    input_type=_QUERY_STATEMENT,
    output_type=_DIRECTORY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER_DIVA)

DESCRIPTOR.services_by_name['server_diva'] = _SERVER_DIVA

# @@protoc_insertion_point(module_scope)
