# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_flask_pb2 as server__flask__pb2


class server_flaskStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.request_frame_path = channel.unary_unary(
        '/server_flask.server_flask/request_frame_path',
        request_serializer=server__flask__pb2.query_statement.SerializeToString,
        response_deserializer=server__flask__pb2.directory.FromString,
        )


class server_flaskServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def request_frame_path(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_server_flaskServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'request_frame_path': grpc.unary_unary_rpc_method_handler(
          servicer.request_frame_path,
          request_deserializer=server__flask__pb2.query_statement.FromString,
          response_serializer=server__flask__pb2.directory.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'server_flask.server_flask', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
