# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_flask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_flask.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12server_flask.proto\"$\n\x14Server_Frame_request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\tdirectory\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t2B\n\x0cserver_flask\x12\x32\n\x0brequest_dir\x12\x15.Server_Frame_request\x1a\n.directory\"\x00\x62\x06proto3')
)




_SERVER_FRAME_REQUEST = _descriptor.Descriptor(
  name='Server_Frame_request',
  full_name='Server_Frame_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Server_Frame_request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=58,
)


_DIRECTORY = _descriptor.Descriptor(
  name='directory',
  full_name='directory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='directory.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Server_Frame_request'] = _SERVER_FRAME_REQUEST
DESCRIPTOR.message_types_by_name['directory'] = _DIRECTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Server_Frame_request = _reflection.GeneratedProtocolMessageType('Server_Frame_request', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_FRAME_REQUEST,
  '__module__' : 'server_flask_pb2'
  # @@protoc_insertion_point(class_scope:Server_Frame_request)
  })
_sym_db.RegisterMessage(Server_Frame_request)

directory = _reflection.GeneratedProtocolMessageType('directory', (_message.Message,), {
  'DESCRIPTOR' : _DIRECTORY,
  '__module__' : 'server_flask_pb2'
  # @@protoc_insertion_point(class_scope:directory)
  })
_sym_db.RegisterMessage(directory)



_SERVER_FLASK = _descriptor.ServiceDescriptor(
  name='server_flask',
  full_name='server_flask',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=152,
  methods=[
  _descriptor.MethodDescriptor(
    name='request_dir',
    full_name='server_flask.request_dir',
    index=0,
    containing_service=None,
    input_type=_SERVER_FRAME_REQUEST,
    output_type=_DIRECTORY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER_FLASK)

DESCRIPTOR.services_by_name['server_flask'] = _SERVER_FLASK

# @@protoc_insertion_point(module_scope)
