FROM nvidia/cuda:10.1-base-ubuntu16.04

COPY docker/install-opencv.sh /tmp

# Install all dependencies for OpenCV
RUN /tmp/install-opencv.sh

RUN python3.6 -m pip install grpcio numpy pillow pandas keras tensorflow sklearn pickle-mixin opencv-python