FROM tensorflow/tensorflow:latest-gpu-py3

COPY docker/install-opencv.sh /tmp

# Install all dependencies for OpenCV
RUN /tmp/install-opencv.sh

RUN python -m pip install grpcio numpy easydict pillow pandas keras sklearn pickle-mixin opencv-python bottle SQLAlchemy
